# Series

In [1]:
import pandas as pd

## Create a Series Object from a List
- A `Series` is a single column of ordered homogenous data (data of the same type).
- A `Series` combines the the best features of a list and a dictionary.
- Pandas assigns an identifier to each value. The identifiers make up the **index** of the `Series`.
- If we do not provide a custom index, Pandas defaults to an ascending numeric index.
- The index starts counting from 0.

In [2]:
ice_cream = ["Tiger Tiger", "Mint", "Orange Creamsicle"]
pd.Series(ice_cream)

0          Tiger Tiger
1                 Mint
2    Orange Creamsicle
dtype: str

- A `Series` output includes the data type (`dtype`) of its values.
- `int64` is a 64-bit integer (whole number occupying 64-bits/8 bytes of memory)

In [3]:
numbers = [3, 4, 56, 8, 23]
pd.Series(numbers)

0     3
1     4
2    56
3     8
4    23
dtype: int64

- A `Series` can contain duplicates.

In [4]:
pd.Series([True, True, False])

0     True
1     True
2    False
dtype: bool

## Create a Series Object from a Dictionary
- The `Series` index does not have to be numeric. It can be a variety of data types.
- If we pass a dictionary to the `Series` constructor, Pandas will use the keys as the index labels.
- Pandas will keep track of each element's order (even if the index is non-numeric).

In [5]:
sushi = {
  "Salmon": "Pink",
  "Uni": "Yellow",
  "Cucumber": "Green"
}
pd.Series(sushi)

Salmon        Pink
Uni         Yellow
Cucumber     Green
dtype: str

## Intro to Series Methods
- A method is a function attached to an object. It is a command we can issue to the object.
- Invoke a method with the `object.method()` syntax.
- A variable is a name for an existing object. Use `variable.method()` in that case.

- The `sum` method adds together the `Series`' values.
- The methods return a `NumPy` scalar value of type `numpy.float64`.
- NumPy is a dependency of Pandas. The `Series` object relies on NumPy's `ndarray` object under the hood.
- JupyterLab prints out the string representation of the NumPy numeric object (`np.float64`)

In [9]:
number_series = pd.Series(numbers)
number_series.sum()

np.int64(94)

- Pass a NumPy object into Python's `print` function to see its user-friendly string representation.

In [13]:
print(number_series.sum())

94

- The `product` method multiplies the `Series`' values.
- The `mean` method calculates the average of the `Series`' values.
- The `std` method calculates the standard deviation of the `Series`' values.

In [14]:
number_series.product()

np.int64(123648)

In [15]:
number_series.mean()

np.float64(18.8)

In [16]:
number_series.std()

22.286767374386088

## Intro to Series Attributes
- An **attribute** is a piece of data that lives on an object.
- An **attribute** is a fact, a detail, a characteristic of the object.
- Access an attribute with `object.attribute` syntax.

- The `size` attribute returns a count of the number of values in the `Series`.

In [17]:
number_series.size

5

- The `is_unique` attribute returns `True` if the `Series` has no duplicate values.

In [18]:
number_series.is_unique

True

- The `index`return the underlying object that hold the `Series`' index labels.
- You can think of a `Series` object as an collection of other objects.
- Some developers use the word "composition" to define this design. An object is composed of other objects.

In [21]:
number_series.index

RangeIndex(start=0, stop=5, step=1)

- Python's `type` function returns the class of a specified value.
- The class is the blueprint that an object is made from.
- The output can reveal the library that defines the class.
- The `RangeIndex` object/class comes from the Pandas library.

In [24]:
type(number_series)

pandas.Series

- The `values` attribute returns the object storing the `Series`'s values.

In [28]:
number_series.values

array([ 3,  4, 56,  8, 23])

## Parameters and Arguments
- A **parameter** is the name for an expected input to a function/method/class instantiation.
- An **argument** is the concrete value we provide for a parameter during invocation.
- We can pass arguments either sequentially (based on parameter order) or with explicit parameter names written out.

- The first parameter for the `Series` constructor is `data`, which represents the values of the `Series`.
- The constructor will provide fallback/default values to the other parameters.
- Use Shift + Tab to see the `Series` documentation and the default values.
- The `Series` values can contain duplicates.

In [29]:
pd.Series(numbers)

0     3
1     4
2    56
3     8
4    23
dtype: int64

- The second parameter for the `Series` constructor is `index`, which holds the index labels.
- Notice that the `Series` index _can_ contain duplicates (although this is not ideal).

In [31]:
pd.Series(numbers, ["three", "four", "fifty-six", "eight", "twenty-three"])

three            3
four             4
fifty-six       56
eight            8
twenty-three    23
dtype: int64

- Reversing the order of arguments results in a different `Series`.
- `weekdays` becomes the argument for `data`, and `fruits` becomes the argument for `index`.

In [32]:
pd.Series(["three", "four", "fifty-six", "eight", "twenty-three"], numbers)

3            three
4             four
56       fifty-six
8            eight
23    twenty-three
dtype: str

- If using keyword arguments, the order does not matter.
- Python matches the parameter to the argument by its name, not by its order.
- Keyword arguments also provide context on what the parameter represents.

In [33]:
pd.Series(index=["three", "four", "fifty-six", "eight", "twenty-three"], data=numbers)

three            3
four             4
fifty-six       56
eight            8
twenty-three    23
dtype: int64

- You can mix-and-match positional arguments with keyword arguments.
- Use keyword arguments to skip required arguments.
- The `name` parameter assigns a name to the `Series`.

In [34]:
pd.Series(name="Some Numbers", data=numbers)

0     3
1     4
2    56
3     8
4    23
Name: Some Numbers, dtype: int64

- A `Series` can be empty. Pandas will assume an `object` data type.

In [36]:
pd.Series(name="Empty One")

Series([], Name: Empty One, dtype: object)

## Import Series with the pd.read_csv Function

### The CSV Format
- A comma-separated values (**CSV**) is a plain text file that uses line breaks to separate rows and commas to separate row values.
- The comma-separated values (CSV) format stores one record per row.
- The CSV format separates each row's values with commas.

```
name,strength,magic,speed
Zorblax,9,2,5
Mira,4,9,8
Thud,10,1,2
Eloria,3,10,7
Sorel,2,,4
```

- Pandas ships with many functions for importing different types of files. Their names begin with `read`.
- The `read_csv` function imports a CSV text file.
- The function accepts 30+ parameters. The first one specifies the file name/path.
- The `read_csv` function imports the dataset as a `DataFrame`, a 2-dimensional table.

In [65]:
heroes = pd.read_csv("./superhero_academy.csv")
print(heroes)

       Hero  Flying  Strength  Stealth  Telepathy  Gadgets
0      Zoom    85.0      70.0       90       60.0       95
1  Mentalis    92.0      55.0       40       88.0       78
2     Titan    45.0      98.0       30        NaN       55
3    Shadow     NaN      82.0       95       75.0       90
4   Psi-Kid    78.0       NaN       65       92.0       45
5   Specter    95.0      60.0       88       35.0       70

- The `usecols` parameter accepts a list of the column(s) to import.
- Pandas still imports the dataset as a 1-column `DataFrame`.

In [44]:
heroes_short = pd.read_csv("./superhero_academy.csv", usecols=[0, 5])
print(heroes_short)

       Hero  Gadgets
0      Zoom       95
1  Mentalis       78
2     Titan       55
3    Shadow       90
4   Psi-Kid       45
5   Specter       70

- The `squeeze` method converts a 1-column `DataFrame` to a `Series`.
- Pass an argument of `columns` to specify the orientation/direction of the compression (squeeze).
- Let's assign the `DataFrame` to a variable like `pokemon`. This will be our import code at the start of each lesson.

In [68]:
hero_frame = heroes.squeeze('columns')
# I don't see what 'columns' does here, because it's the same either way
hero_frame

       Hero  Flying  Strength  Stealth  Telepathy  Gadgets
0      Zoom    85.0      70.0       90       60.0       95
1  Mentalis    92.0      55.0       40       88.0       78
2     Titan    45.0      98.0       30        NaN       55
3    Shadow     NaN      82.0       95       75.0       90
4   Psi-Kid    78.0       NaN       65       92.0       45
5   Specter    95.0      60.0       88       35.0       70

## The head and tail Methods
- The `head` method returns a number of rows from the top/beginning of the `Series`.
- The `tail` method returns a number of rows from the bottom/end of the `Series`.

In [61]:
heroes.head(1)

   Hero  Flying  Strength  Stealth  Telepathy  Gadgets
0  Zoom    85.0      70.0       90       60.0       95

In [62]:
heroes.tail(1)

      Hero  Flying  Strength  Stealth  Telepathy  Gadgets
5  Specter    95.0      60.0       88       35.0       70

## Passing Series to Python's Built-In Functions
- Python's functions support Pandas objects as arguments.

- The `len` function returns the length of the `Series`.

In [56]:
len(heroes)

6

- The `type` function returns the type of an object.
- `type` can help identify the library that an object is coming from.

In [72]:
print(type(heroes))
print(type(number_series))

<class 'pandas.DataFrame'>
<class 'pandas.Series'>

- The `list` function converts the `Series` to a list.

In [74]:
list(number_series)

[3, 4, 56, 8, 23]

- The `sorted` function converts the `Series` to a sorted list.

In [75]:
sorted(number_series)

[3, 4, 8, 23, 56]

- The `dict` function converts the `Series` to a dictionary.
- The index labels become the keys.

In [76]:
dict(number_series)

{0: np.int64(3),
 1: np.int64(4),
 2: np.int64(56),
 3: np.int64(8),
 4: np.int64(23)}

- The `max` function returns the largest value in the `Series`.
- The `min` function returns the smallest value in the `Series`.
- The largest value in a string `Series` is the string closest to the end of the alphabet.

In [77]:
max(number_series)

56

In [78]:
min(number_series)

3

- The `dir` function returns a list of strings with the object's attributes/methods.

In [79]:
dir(number_series)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_attrs',
 '_binop',
 '_can_hold_na',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'between',
 'between_time',
 'bfill',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

## Check for Inclusion with Python's in Keyword
- The `in` keyword checks if a value exists within an object.
- The `in` keyword will look for a value in the `Series`'s index.
- Use the `index` and `array` attributes to access "nested" objects within the `Series`.
- Combine the `in` keyword with `array` to search within the `Series`'s values.

In [80]:
3 in number_series

True

- Use the `array` attribute to access the underlying object storing the `Series` data.
- The object may vary but it should support Python's `in` keyword to check for inclusion.
- The `values` attribute also works, but the Pandas documentation recommends `array`.

In [81]:
number_series.array

<NumpyExtensionArray>
[3, 4, 56, 8, 23]
Length: 5, dtype: int64

## The sort_values Method
- The `sort_values` method sorts a `Series's` values in order.
- By default, pandas applies an ascending sort (smallest to largest).
- Customize the sort order with the `ascending` parameter.
- The index positions/labels will move with the values.

In [83]:
number_series.sort_values(ascending=False)

2    56
4    23
3     8
1     4
0     3
dtype: int64

## The sort_index Method
- The `sort_index` method sorts a `Series` by its index.
- The `sort_index` method also accepts an `ascending` parameter to set the sort order.

In [85]:
number_series.sort_index(ascending=False)

4    23
3     8
2    56
1     4
0     3
dtype: int64

- The `index_col` parameter to `read_csv` sets the index column.

In [86]:
heroes_by_gadget = pd.read_csv('./superhero_academy.csv', index_col=5)
heroes_by_gadget

             Hero  Flying  Strength  Stealth  Telepathy
Gadgets
95           Zoom    85.0      70.0       90       60.0
78       Mentalis    92.0      55.0       40       88.0
55          Titan    45.0      98.0       30        NaN
90         Shadow     NaN      82.0       95       75.0
45        Psi-Kid    78.0       NaN       65       92.0
70        Specter    95.0      60.0       88       35.0

## Extract Series Value by Index Position
- Use the `iloc` accessor to extract a `Series` value by its index position.
- `iloc` is short for "index location".

In [87]:
number_series.iloc

- Provide square brackets after the accessor. Declare the index position inside the square brackets.

In [88]:
number_series.iloc[2]

np.int64(56)

- A nonexistent index will trigger an exception.

In [90]:
number_series.iloc[-1]

np.int64(23)

- Pass a Python list to extract multiple `Series` values by their index positions.

In [95]:
number_series.iloc[[1,2]]

1     4
2    56
dtype: int64

- The `Series` support's Python's list slicing syntaxes (slices, slices from start, slices to end, etc.) are supported with `Series` objects.

In [97]:
number_series.iloc[:2]

0    3
1    4
dtype: int64

- Pandas also supports negative values and negative slices.
- -1 pulls the last value, -10 pulls the value 10 from the end.
- The second number is exclusive. `-10:-5` will pull the value 10 from the end up until (but not including) 5 from the end.

- The `iat` accessor accepts only a single index value.
- The `iat` accessor does _not_ support lists or slices.
- The advantage of the restriction is that access is generally faster than `iloc`.
- Pandas does not need to figure out the argument type.

In [98]:
number_series.iat[3]

np.int64(8)

## Extract Series Value by Index Label
- Use the `loc` accessor to extract a `Series` value by its index label.
- Pass a list to extract multiple values by index label.
- If one index label/position in the list does not exist, Pandas will raise an error.

In [99]:
number_series.loc[2]

np.int64(56)

In [100]:
number_series.loc[[2,4]]

2    56
4    23
dtype: int64

- The `at` accessor is complementary to `loc`, much like `iat` is complementary to `iloc`.
- It only supports a single index label. It does not support slices or lists. The constraint enables it to be faster for single-index targets.

In [101]:
number_series.at[0]

np.int64(3)

## The get Method on a Series
- The `get` method extracts a `Series` value by index label. It is an alternative option to square brackets.

In [102]:
number_series.get(9)

In [103]:
number_series.get(1)

np.int64(4)

- The `get` method accepts a list of multiple index labels.

In [104]:
number_series.get([3,4])

3     8
4    23
dtype: int64

- Square brackets raise an exception if the key does not exist.
- The `get` method's second argument sets the fallback value to return if the label/position does not exist.
- The default value for the default is `None`, which has no printed representation.

- We can also a pass list to extract multiple elements.

## Overwrite a Series Value
- Use the `loc`/`iloc` accessor to target an index label/position, then use an equal sign to provide a new value.

In [107]:
number_series.loc[0] = 69

In [106]:
number_series

0    69
1     4
2    56
3     8
4    23
dtype: int64

- The `Series` maintains a numeric order of values even if the index is not numeric.

## Copy-on-Write and the copy Method
- In earlier versions of Pandas (`< 3.0`), targeting data could return a view.
- A view was a window/alternate perspective into the *same* underlying data.
- Changes to the view would mutate the original object that the view was referencing.
- Pandas 3.0 follows a **Copy-on-Write** principle.
    1. Any object derived from another behaves as an independent copy.
    2. When code mutates the underlying data, Pandas will create a copy to avoid unexpected side effects.
- A **copy** is a duplicate/clone of an object.

- Let's assign the imported `DataFrame` to a `pokemon_df` variable.
- We'll then use it as the basis of creating a `Series` assigned to `pokemon_series`.
- `pokemon_series` share the same data under the hood as the `DataFrame`.
- Pandas has no reason to copy the data yet (and use more memory).

In [109]:
number_df = pd.DataFrame(numbers)
number_df

    0
0   3
1   4
2  56
3   8
4  23

In [110]:
number_series

0    69
1     4
2    56
3     8
4    23
dtype: int64

- Let's use the `iloc` accesor to update the `Series` at index position 0.
- Pandas sees the mutation of the underlying data. It creates a copy of the data for the `Series`.

In [112]:
number_series.iloc[0] = 1
number_series

0     1
1     4
2    56
3     8
4    23
dtype: int64

- The original `pokemon_df` `DataFrame` is **not** mutated.
- The Copy-on-Write principle in Pandas 3 force a copy of the `Series` data when we mutate it (`iloc`).
- `pokemon_series` _was_ relying on shared data before `iloc` but now has its own copy of the data.

In [113]:
number_df

    0
0   3
1   4
2  56
3   8
4  23

- In previous version of Pandas, we would see different behavior.
- Mutating the `Series` would mutate the `DataFrame` as well.
- In previous versions, invoke the `copy` method explicitly to force a copy of the `Series` data.

## Math Methods on Series

In [115]:
number_series.count()

np.int64(5)

- The `count` method returns the number of present values in the `Series`.
- The `count` method excludes missing values.
- The `size` attribute includes missing values (the `len` function is another option).

In [116]:
number_series.size

5

- The `sum` method adds together the `Series`'s values.

In [117]:
number_series.sum()

np.int64(92)

- The `product` method multiplies together the `Series`'s values.

In [118]:
number_series.product()

np.int64(41216)

- The `mean` method calculates the average of the `Series`'s values.

In [119]:
number_series.mean()

np.float64(18.4)

- The `std` method calculates the standard deviation of the `Series`'s values.

In [120]:
number_series.std()

22.656124999655173

- The `max` method returns the largest value in the `Series`.
- The `min` method returns the smallest value in the `Series`.

In [121]:
number_series.min()

1

- The `idxmin` and `idxmax` methods return the index label where the smallest/largest value occurs.

In [123]:
number_series.idxmax()

2

- We can confirm the value is correct by extracting it by the index.

In [124]:
number_series[2]

np.int64(56)


- The `median` method returns the median of the `Series` (the value in the middle).

In [126]:
number_series.median()

8.0

- The `mode` method returns the mode of the `Series` (the most frequent value).

In [125]:
number_series.mode()

0     1
1     4
2     8
3    23
4    56
dtype: int64

- The `describe` method returns a summary with various mathematical calculations.
- The output includes the quartiles. 25% of the values are less than or equal to 13.295.

In [127]:
number_series.describe()

count     5.000000
mean     18.400000
std      22.656125
min       1.000000
25%       4.000000
50%       8.000000
75%      23.000000
max      56.000000
dtype: float64

- The `quantile` method returns any percentile.
- The argument should be a decimal between 0 and 1.

In [129]:
number_series.quantile(0.15)

np.float64(2.8)

- The `quantile` method accepts a list of multiple percentiles.
- Pandas will return a `Series`. The index labels will be the percentiles.

In [130]:
number_series.quantile([0.1, 0.2])

0.1    2.2
0.2    3.4
dtype: float64

## Broadcasting
- **Broadcasting** is the process of applying a consistent mathematical operation to every `Series` value.
- Use a mathematical operator with a `Series` to apply the mathematical operation to every value.
- There are also methods to accomplish the same results (`add`, `sub`, `mul`, `div`, etc.)

In [131]:
number_series.mul(100)

0     100
1     400
2    5600
3     800
4    2300
dtype: int64

- Wrap the operation in parentheses to invoke a method upon the resulting object.
- Alternatively, assign the result to a variable.

In [132]:
(number_series.divide(100)).subtract(1)

0   -0.99
1   -0.96
2   -0.44
3   -0.92
4   -0.77
dtype: float64

- Use `-` for subtraction, `*` for multiplication, `/` for division, and `//` for floor division.
- We can reverse the operands around the operator if the operation is logically the same.

In [133]:
number_series + 2

0     3
1     6
2    58
3    10
4    25
dtype: int64

## Pandas Aligns by Index Label
- We can perform mathematical operations between multiple `Series`.
- Pandas will align values by index labels, not by position.
- The resulting index will be the union (combination) of all index labels from the two `Series`.
- `NaN` is Pandas' designation for a missing value.
- Any label present in one `Series` but missing in the other produces `NaN` in the result. Pandas cannot add "unknown" to a valid numeric value.

In [134]:
number_series * number_series

0       1
1      16
2    3136
3      64
4     529
dtype: int64

In [135]:
revenue_ny = pd.Series([100, 200, 300], index=["Mon", "Tue", "Wed"])
revenue_ny

Mon    100
Tue    200
Wed    300
dtype: int64

In [136]:
revenue_la = pd.Series([50, 60, 70], index=["Tue", "Wed", "Thu"])
revenue_la

Tue    50
Wed    60
Thu    70
dtype: int64

- Let's find the total business revenue per day/index label.
- The `Tue` and `Wed` labels are found in both `Series.`
- The `Mon` label is only found in `revenue_ny`.
- The `Thu` label is only found in `revenue_la`.

In [137]:
revenue_ny + revenue_la

Mon      NaN
Thu      NaN
Tue    250.0
Wed    360.0
dtype: float64

- The `add` method supports a `fill_value` parameter to provide a fallback value for missing labels.
- Pandas will assign the present label value with the `fill_value`.

In [138]:
revenue_ny.add(revenue_la, fill_value=0)

Mon    100.0
Thu     70.0
Tue    250.0
Wed    360.0
dtype: float64

## The value_counts Method
- The `value_counts` method returns the number of times that each distinct value occurs in the `Series`.

In [139]:
pokemon = pd.read_csv("pokemon.csv", index_col="Name").squeeze("columns")
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

- Pandas returns the values in descending order (most frequent first).

In [140]:
pokemon.value_counts()

Type
Water               74
Normal              74
Grass               46
Psychic             39
Fire                36
                    ..
Rock, Electric       1
Dark, Ground         1
Dragon, Dark         1
Fairy, Fighting      1
Fighting, Dragon     1
Name: count, Length: 200, dtype: int64

- The `ascending` parameter customizes the sort order. An ascending sort places the smallest values first.

In [141]:
pokemon.value_counts(ascending=True)

Type
Steel, Ground     1
Fire, Rock        1
Rock, Dark        1
Bug, Ground       1
Bug, Ghost        1
                 ..
Fire             36
Psychic          39
Grass            46
Water            74
Normal           74
Name: count, Length: 200, dtype: int64

- The `normalize` parameter returns the relative frequencies/percentages of the values instead of the counts.
- Multiply by 100% to get the percentage.

In [142]:
pokemon.value_counts(normalize=True)

Type
Water               0.073267
Normal              0.073267
Grass               0.045545
Psychic             0.038614
Fire                0.035644
                      ...
Rock, Electric      0.000990
Dark, Ground        0.000990
Dragon, Dark        0.000990
Fairy, Fighting     0.000990
Fighting, Dragon    0.000990
Name: proportion, Length: 200, dtype: float64

In [143]:
pokemon.value_counts(normalize=True).mul(100).round(2)

Type
Water               7.33
Normal              7.33
Grass               4.55
Psychic             3.86
Fire                3.56
                    ...
Rock, Electric      0.10
Dark, Ground        0.10
Dragon, Dark        0.10
Fairy, Fighting     0.10
Fighting, Dragon    0.10
Name: proportion, Length: 200, dtype: float64

## The apply Method
- The `apply` method invokes a function on every `Series` value.
- The method accepts the _uninvoked_ function.

- The `apply` method supports custom functions as well.
- A pandas method for an operation will usually be faster.
- But, if you don't know the right pandas method and can write the logic in Python, `apply` is a great workaround.

In [ ]:
pokemon.apply(len).sort_values(ascending=False)
## This was confusing, but it's the length of the values, 
# which is the types in this case

Name
Pawmo         18
Pawmot        18
Iron Hands    18
Gallade       17
Medicham      17
              ..
Beartic        3
Cryogonal      3
Shelmet        3
Accelgor       3
Spewpa         3
Name: Type, Length: 1010, dtype: int64

## The map Method
- The `map` method associates or connects each `Series` value to another value.
- We can pass the method a dictionary or a `Series`. Both types connect keys to values.
- The `map` method uses our argument to connect or bridge together the values.

- Let's define a dictionary mapping types to attack powers.

In [149]:
attack_powers = {
    "Grass": 10,
    "Fire": 15,
    "Water": 18,
    "Fairy, Fighting": 20,
    "Grass, Psychic": 50,
}

- Pandas will map/connect each `Series` index label to the complementary dictionary value by matching the key.

In [150]:
pokemon.map(attack_powers)

Name
Bulbasaur        NaN
Ivysaur          NaN
Venusaur         NaN
Charmander      15.0
Charmeleon      15.0
                ...
Iron Valiant    20.0
Koraidon         NaN
Miraidon         NaN
Walking Wake     NaN
Iron Leaves     50.0
Name: Type, Length: 1010, dtype: float64

In [151]:
attack_powers_series = pd.Series(attack_powers)
attack_powers_series

Grass              10
Fire               15
Water              18
Fairy, Fighting    20
Grass, Psychic     50
dtype: int64

- The `map` method also accepts another `Series` as an argument.
- Pandas will map the index labels from `pokemon` to the index labels in `attack_powers_series`.
- It will match the corresponding attack power value for each Pokemon.

In [152]:
pokemon.map(attack_powers_series)

Name
Bulbasaur        NaN
Ivysaur          NaN
Venusaur         NaN
Charmander      15.0
Charmeleon      15.0
                ...
Iron Valiant    20.0
Koraidon         NaN
Miraidon         NaN
Walking Wake     NaN
Iron Leaves     50.0
Name: Type, Length: 1010, dtype: float64