# DataFrames III: Data Extraction

In [1]:
import pandas as pd

## This Module's Dataset
- This module's dataset is a collection of all James Bond movies.

In [2]:
movies = pd.read_csv("jamesbond.csv")
movies.tail()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

## The set_index and reset_index Methods
- The index serves as the collection of primary identifiers/labels/entrypoints for the rows.
- The fastest way to extract a row is from a sorted index by position/label.
- Pandas uses index labels/values when merging different objects together.
- The `set_index` method sets an existing column as the index of the `DataFrame`.
- The `reset_index` method uses the standard numeric index as the index of the `DataFrame`.

In [4]:
movies.set_index("Year").head()

,Film,Actor,Director,Box Office,Budget,Bond Actor Salary
Year,,,,,,
1962,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
1963,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
1964,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
1965,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
1967,Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN

In [ ]:
# NOTE: Setting the index didn't update the original data frame
movies.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [ ]:
# But this seems to add a weird index series in addition to the regular index
movies.reset_index().head()

,index,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

## Retrieve Rows by Index Position and Index Label
- The `iloc` accessor retrieves one or more rows by index position.
- The `loc` accessor retrieves one or more rows by index label.
- Provide a pair of square brackets after the accessor.
- The accessors accept single values, lists, and slices.

In [9]:
movies.iloc[4]

Film                 Casino Royale
Year                          1967
Actor                  David Niven
Director                Ken Hughes
Box Office                   315.0
Budget                        85.0
Bond Actor Salary              NaN
Name: 4, dtype: object

In [11]:
movies.iloc[3:5] # Not inclusive!

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [13]:
movies_by_title = movies.set_index("Film")
movies_by_title.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [14]:
movies_by_title.loc["Thunderball"]

Year                          1965
Actor                 Sean Connery
Director             Terence Young
Box Office                   848.1
Budget                        41.9
Bond Actor Salary              4.7
Name: Thunderball, dtype: object

In [ ]:
# I expected this to get a range, but it just returns the two. :(
movies_by_title.loc["Goldfinger":"Thunderball"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7

## Second Arguments to loc and iloc Accessors
- The second value inside the square brackets targets the columns.
- The `loc` accessor accepts index labels for the rows and columns.
- The `iloc` accessor accepts numeric index positions for the rows and columns.

In [20]:
movies_by_title.loc["GoldenEye", ["Year", "Actor"]]

Year               1995
Actor    Pierce Brosnan
Name: GoldenEye, dtype: object

In [24]:
movies.iloc[4, 1]

np.int64(1967)

In [25]:
movies.iloc[4, [1,3,5]]

Year              1967
Director    Ken Hughes
Budget            85.0
Name: 4, dtype: object

## Overwrite Value in a DataFrame
- Use the `iloc` or `loc` accessor on the `DataFrame` to target a value, then provide the equal sign and a new value.

In [26]:
movies_by_title.loc["GoldenEye"]

Year                            1995
Actor                 Pierce Brosnan
Director             Martin Campbell
Box Office                     518.5
Budget                          76.9
Bond Actor Salary                5.1
Name: GoldenEye, dtype: object

In [27]:
movies_by_title.loc["GoldenEye", "Actor"] = "James Dean"
movies_by_title.loc["GoldenEye"]

Year                            1995
Actor                     James Dean
Director             Martin Campbell
Box Office                     518.5
Budget                          76.9
Bond Actor Salary                5.1
Name: GoldenEye, dtype: object

- The `replace` method replaces all occurrences of a value with another value (think of it like "Find and Replace").

In [30]:
# Whoa! I can use dot notation instead of the strings for series. Much nicer.
movies_by_title.Actor = movies_by_title.Actor.replace("James Dean", "Me!")
movies_by_title.loc["GoldenEye"]

Year                            1995
Actor                            Me!
Director             Martin Campbell
Box Office                     518.5
Budget                          76.9
Bond Actor Salary                5.1
Name: GoldenEye, dtype: object

- To overwrite multiple values in a `DataFrame`, use an accessor on the `DataFrame` itself.
- Pandas uses **Copy-on-Write**: any subset derived from a `DataFrame` behaves as a copy, not a view.
- Because the intermediate result is a copy, the assignment updates the copy — not the original `DataFrame`.
- Pandas raises a `ChainedAssignmentError` to warn you the operation had no effect.
- Accessors like `loc` and `iloc` can accept Boolean Series. Use them to target the values to overwrite.

In [33]:
movies_by_title.loc[movies_by_title.Actor == "Sean Connery", "Actor"] = "Henry Walton Jones Senior"
movies_by_title

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Henry Walton Jones Senior,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Henry Walton Jones Senior,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Henry Walton Jones Senior,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Henry Walton Jones Senior,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Henry Walton Jones Senior,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Henry Walton Jones Senior,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Henry Walton Jones Senior,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Me!,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

## Rename Index Labels or Columns in a DataFrame
- The `rename` method accepts a dictionary for either its `columns` or `index` parameters.
- The dictionary keys represent the existing names and the values represent the new names.
- We can replace all columns by overwriting the `DataFrame`'s `columns` attribute.

In [38]:
# This only works because the index is the title.
# Tried with int index and did nothing.
movies_by_title.rename(index={
  "GoldenEye": "Goldeneye"
})

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Henry Walton Jones Senior,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Henry Walton Jones Senior,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Henry Walton Jones Senior,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Henry Walton Jones Senior,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Henry Walton Jones Senior,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Henry Walton Jones Senior,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Henry Walton Jones Senior,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Goldeneye,1995,Me!,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [40]:
movies.rename(columns={
  "Actor":"Who Played Bond"
}).head()

,Film,Year,Who Played Bond,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [42]:
# Note it didn't change the original
movies.columns

Index(['Film', 'Year', 'Actor', 'Director', 'Box Office', 'Budget',
       'Bond Actor Salary'],
      dtype='str')

## Delete Rows or Columns from a DataFrame
- The `drop` method deletes one or more rows/columns from a `DataFrame`.
- Pass the `index` or `columns` parameters a list of the column names to remove.

In [44]:
movies_by_title.drop(columns=["Year"]).head()

,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,
Dr. No,Henry Walton Jones Senior,Terence Young,448.8,7.0,0.6
From Russia with Love,Henry Walton Jones Senior,Terence Young,543.8,12.6,1.6
Goldfinger,Henry Walton Jones Senior,Guy Hamilton,820.4,18.6,3.2
Thunderball,Henry Walton Jones Senior,Terence Young,848.1,41.9,4.7
Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN

In [47]:
# Just drops the one row
movies_by_title.drop(index=["A View to a Kill"]).head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Henry Walton Jones Senior,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Henry Walton Jones Senior,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Henry Walton Jones Senior,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Henry Walton Jones Senior,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

- The `pop` method removes and returns a single `Series` (it mutates the `DataFrame` in the process).
- Python's `del` keyword also removes a single `Series`.

In [48]:
# This one actually changes the dataframe!
actors = movies.pop("Actor")
actors

0       Sean Connery
1       Sean Connery
2       Sean Connery
3       Sean Connery
4        David Niven
5       Sean Connery
6     George Lazenby
7       Sean Connery
8        Roger Moore
9        Roger Moore
10       Roger Moore
11       Roger Moore
12       Roger Moore
13      Sean Connery
14       Roger Moore
15       Roger Moore
16    Timothy Dalton
17    Timothy Dalton
18    Pierce Brosnan
19    Pierce Brosnan
20    Pierce Brosnan
21    Pierce Brosnan
22      Daniel Craig
23      Daniel Craig
24      Daniel Craig
25      Daniel Craig
26      Daniel Craig
Name: Actor, dtype: str

In [50]:
# No more actor column!
movies.head()

,Film,Year,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,Ken Hughes,315.0,85.0,NaN

## Create Random Sample with the sample Method
- The `sample` method returns a specified one or more random rows from the `DataFrame`.
- Customize the `axis` parameter to extract random columns.

In [ ]:
# Single sample
movies_by_title.sample()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1

In [54]:
movies_by_title.sample(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
You Only Live Twice,1967,Henry Walton Jones Senior,Lewis Gilbert,514.2,59.9,4.4
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN

In [57]:
movies_by_title.sample(frac=0.25) # oh, 25% of the total rows

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Henry Walton Jones Senior,Terence Young,848.1,41.9,4.7
GoldenEye,1995,Me!,Martin Campbell,518.5,76.9,5.1
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9

In [60]:
# Any two example columns
movies_by_title.sample(n=2, axis="columns")

                                                     Actor  Budget
Film
Dr. No                           Henry Walton Jones Senior     7.0
From Russia with Love            Henry Walton Jones Senior    12.6
Goldfinger                       Henry Walton Jones Senior    18.6
Thunderball                      Henry Walton Jones Senior    41.9
Casino Royale                                  David Niven    85.0
You Only Live Twice              Henry Walton Jones Senior    59.9
On Her Majesty's Secret Service             George Lazenby    37.3
Diamonds Are Forever             Henry Walton Jones Senior    34.7
Live and Let Die                               Roger Moore    30.8
The Man with the Golden Gun                    Roger Moore    27.7
The Spy Who Loved Me                           Roger Moore    45.1
Moonraker                                      Roger Moore    91.5
For Your Eyes Only                             Roger Moore    60.2
Never Say Never Again            Henry Walton Jones Senior    86.0
Octopussy                                      Roger Moore    53.9
A View to a Kill                               Roger Moore    54.5
The Living Daylights                        Timothy Dalton    68.8
Licence to Kill                             Timothy Dalton    56.7
GoldenEye                                              Me!    76.9
Tomorrow Never Dies                         Pierce Brosnan   133.9
The World Is Not Enough                     Pierce Brosnan   158.3
Die Another Day                             Pierce Brosnan   154.2
Casino Royale                                 Daniel Craig   145.3
Quantum of Solace                             Daniel Craig   181.4
Skyfall                                       Daniel Craig   170.2
Spectre                                       Daniel Craig   206.3
No Time to Die                                Daniel Craig   301.0

## The nsmallest and nlargest Methods
- The `nlargest` method returns a specified number of rows with the largest values from a given column.
- The `nsmallest` method returns rows with the smallest values from a given column.
- The `nlargest` and `nsmallest` methods are more efficient than sorting the entire `DataFrame`.

In [61]:
movies_by_title.nlargest(n=4, columns="Box Office")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Henry Walton Jones Senior,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Henry Walton Jones Senior,Guy Hamilton,820.4,18.6,3.2
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [ ]:
movies_by_title.Budget.nlargest(2) # also works, but returns series, not data frame

Film
No Time to Die    301.0
Spectre           206.3
Name: Budget, dtype: float64

## The clip Method
- The `clip` method trims values at specified lower and/or upper thresholds.
- Values below `lower` are set to `lower`; values above `upper` are set to `upper`.

In [64]:
# Doesn't do anything for NaN
movies_by_title["Bond Actor Salary"].clip(lower=5, upper=10)

Film
Dr. No                              5.0
From Russia with Love               5.0
Goldfinger                          5.0
Thunderball                         5.0
Casino Royale                       NaN
You Only Live Twice                 5.0
On Her Majesty's Secret Service     5.0
Diamonds Are Forever                5.8
Live and Let Die                    NaN
The Man with the Golden Gun         NaN
The Spy Who Loved Me                NaN
Moonraker                           NaN
For Your Eyes Only                  NaN
Never Say Never Again               NaN
Octopussy                           7.8
A View to a Kill                    9.1
The Living Daylights                5.2
Licence to Kill                     7.9
GoldenEye                           5.1
Tomorrow Never Dies                10.0
The World Is Not Enough            10.0
Die Another Day                    10.0
Casino Royale                       5.0
Quantum of Solace                   8.1
Skyfall                            10.0
Spectre                            10.0
No Time to Die                     10.0
Name: Bond Actor Salary, dtype: float64

## The apply Method with DataFrames
- The `apply` method invokes a function on every column or every row in the `DataFrame`.
- Pass the uninvoked function as the first argument to the `apply` method.

- Pass the `axis` parameter an argument of `"columns"` to invoke the function on every row.
- Pandas will pass in the row's values as a `Series` object. We can use accessors like `loc` and `iloc` to extract the column's values for that row.

In [74]:
movies_by_title = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()

In [75]:
def find_sean_connery(movie):
  if movie.loc["Actor"] == "Sean Connery":
    return "Found him!"
  return "He's missing."

In [76]:
movies_by_title.apply(find_sean_connery, axis="columns")

Film
A View to a Kill                   He's missing.
Casino Royale                      He's missing.
Casino Royale                      He's missing.
Diamonds Are Forever                  Found him!
Die Another Day                    He's missing.
Dr. No                                Found him!
For Your Eyes Only                 He's missing.
From Russia with Love                 Found him!
GoldenEye                          He's missing.
Goldfinger                            Found him!
Licence to Kill                    He's missing.
Live and Let Die                   He's missing.
Moonraker                          He's missing.
Never Say Never Again                 Found him!
No Time to Die                     He's missing.
Octopussy                          He's missing.
On Her Majesty's Secret Service    He's missing.
Quantum of Solace                  He's missing.
Skyfall                            He's missing.
Spectre                            He's missing.
The Living Daylights               He's missing.
The Man with the Golden Gun        He's missing.
The Spy Who Loved Me               He's missing.
The World Is Not Enough            He's missing.
Thunderball                           Found him!
Tomorrow Never Dies                He's missing.
You Only Live Twice                   Found him!
dtype: str