# MultiIndex

In [1]:
import pandas as pd

## This Module's Dataset

In [2]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d")
bigmac.head()

        Date      Country  Price in US Dollars
0 2000-04-01    Argentina             2.500000
1 2000-04-01    Australia             1.541667
2 2000-04-01       Brazil             1.648045
3 2000-04-01       Canada             1.938776
4 2000-04-01  Switzerland             3.470588

## Create a MultiIndex
- A `MultiIndex` is an index with multiple levels or layers.
- Pass the `set_index` method a list of column names to create a multi-index `DataFrame`.
- The order of the list's values will determine the order of the levels.
- Alternatively, we can pass the `read_csv` function's `index_col` parameter a list of columns.

In [ ]:
# if you don't do sort_index, they're still scrambled
# This also doesn't change the original, it just passes back a copy
bigmac_indexed = bigmac.set_index(["Country", "Date"]).sort_index()
bigmac_indexed

                      Price in US Dollars
Country   Date
Argentina 2000-04-01             2.500000
          2001-04-01             2.500000
          2002-04-01             0.798722
          2003-04-01             1.423611
          2004-05-01             1.477966
...                                   ...
Vietnam   2018-07-01             2.821242
          2019-01-01             2.801845
          2019-07-09             2.797985
          2020-01-14             2.847774
          2020-07-01             2.847282

[1386 rows x 1 columns]

## Extract and Rename Index Level Values
- The `get_level_values` method extracts an `Index` with the values from one level in the `MultiIndex`.
- Invoke the `get_level_values` on the `MultiIndex`, not the `DataFrame` itself.
- The method expects either the level's index position or its name.

In [10]:
bigmac_indexed.index.names

FrozenList(['Country', 'Date'])

In [13]:
bigmac_indexed.index.get_level_values("Country").unique()

Index(['Argentina', 'Australia', 'Azerbaijan', 'Bahrain', 'Brazil', 'Britain',
       'Canada', 'Chile', 'China', 'Colombia', 'Costa Rica', 'Croatia',
       'Czech Republic', 'Denmark', 'Egypt', 'Euro area', 'Guatemala',
       'Honduras', 'Hong Kong', 'Hungary', 'India', 'Indonesia', 'Israel',
       'Japan', 'Jordan', 'Kuwait', 'Lebanon', 'Malaysia', 'Mexico', 'Moldova',
       'New Zealand', 'Nicaragua', 'Norway', 'Oman', 'Pakistan', 'Peru',
       'Philippines', 'Poland', 'Qatar', 'Romania', 'Russia', 'Saudi Arabia',
       'Singapore', 'South Africa', 'South Korea', 'Sri Lanka', 'Sweden',
       'Switzerland', 'Taiwan', 'Thailand', 'Turkey', 'UAE', 'Ukraine',
       'United Arab Emirates', 'United States', 'Uruguay', 'Vietnam'],
      dtype='str', name='Country')

In [ ]:
# Can also do by index of indices.
bigmac_indexed.index.get_level_values(1).unique()

DatetimeIndex(['2000-04-01', '2001-04-01', '2002-04-01', '2003-04-01',
               '2004-05-01', '2005-06-01', '2006-01-01', '2006-05-01',
               '2007-01-01', '2007-06-01', '2008-06-01', '2009-07-01',
               '2010-01-01', '2010-07-01', '2011-07-01', '2012-01-01',
               '2012-07-01', '2013-01-01', '2013-07-01', '2014-01-01',
               '2014-07-01', '2015-01-01', '2015-07-01', '2016-01-01',
               '2016-07-01', '2017-01-01', '2017-07-01', '2018-01-01',
               '2018-07-01', '2019-01-01', '2019-07-09', '2020-01-14',
               '2020-07-01'],
              dtype='datetime64[us]', name='Date', freq=None)

- Invoke the `set_names` method on the `MultiIndex` to change one or more level names.
- Use the `names` and `level` parameter to target a nested index at a given level.
- Alternatively, pass `names` a list of strings to overwrite *all* level names.
- The `set_names` method returns a copy, so replace the original index to alter the `DataFrame`.

In [33]:
temp = bigmac_indexed
temp.index = temp.index.set_names(names="Location", level=0)
temp.head()

                      Price in US Dollars
Location  Date
Argentina 2000-04-01             2.500000
          2001-04-01             2.500000
          2002-04-01             0.798722
          2003-04-01             1.423611
          2004-05-01             1.477966

In [34]:
bigmac_indexed.index = bigmac_indexed.index.set_names(names=["Country", "Date"])
bigmac_indexed.head()

                      Price in US Dollars
Country   Date
Argentina 2000-04-01             2.500000
          2001-04-01             2.500000
          2002-04-01             0.798722
          2003-04-01             1.423611
          2004-05-01             1.477966

## Extract Rows from a MultiIndex DataFrame
- A `tuple` is an immutable list. It cannot be modified after creation.
- Create a tuple with a comma between elements. The Python community convention is to wrap the elements in parentheses.
- The `iloc` and `loc` accessors are available to extract rows by index position or label.
- For the `loc` accessor, pass a tuple to hold the labels from the index levels.

In [ ]:
bigmac.loc[1] # gets the first row in dataframe

Date                   2000-04-01 00:00:00
Country                          Australia
Price in US Dollars               1.541667
Name: 1, dtype: object

In [46]:
# but for dual-indexed dataframes... use one of the indexes
bigmac_indexed.loc["Argentina"].head()

            Price in US Dollars
Date
2000-04-01             2.500000
2001-04-01             2.500000
2002-04-01             0.798722
2003-04-01             1.423611
2004-05-01             1.477966

In [ ]:
# or both the indexes. ORDER MATTERS!
bigmac_indexed.loc["Canada", "2002-04-01"]

Price in US Dollars    2.121019
Name: (Canada, 2002-04-01 00:00:00), dtype: float64

In [51]:
# Can also ask for a column (would make sense if there were more than one)
bigmac_indexed.loc["Vietnam", "Price in US Dollars"]

Date
2014-07-01    2.826189
2015-01-01    2.806361
2015-07-01    2.751032
2016-01-01    2.670524
2016-07-01    2.690583
2017-01-01    2.658161
2017-07-01    2.639393
2018-01-01    2.861986
2018-07-01    2.821242
2019-01-01    2.801845
2019-07-09    2.797985
2020-01-14    2.847774
2020-07-01    2.847282
Name: Price in US Dollars, dtype: float64

## The xs Method
- The `xs` (cross-section) method selects data at a particular level of a `MultiIndex`.
- Pass the `level` parameter the index name or position to target.
- By default, the matched level is dropped from the result. Pass `drop_level=False` to retain it.

In [ ]:
# I find this counterintuitive. It's dropping (selecting?) the level you choose.
bigmac_indexed.xs("2010-01-01", level="Date")

                Price in US Dollars
Country
Argentina                  1.842833
Australia                  3.977870
Brazil                     4.758313
Britain                    3.671328
Canada                     3.973765
Chile                      3.180282
China                      1.830912
Colombia                   3.912960
Costa Rica                 3.518890
Czech Republic             3.714432
Denmark                    5.993859
Egypt                      2.378774
Euro area                  4.843944
Hong Kong                  1.908065
Hungary                    3.857471
Indonesia                  2.242489
Israel                     3.991962
Japan                      3.495740
Malaysia                   2.081181
Mexico                     2.497317
New Zealand                3.611306
Norway                     7.023027
Pakistan                   2.421308
Peru                       2.806480
Philippines                2.210801
Poland                     2.856488
Russia                     2.339025
Saudi Arabia               2.666524
Singapore                  3.188707
South Africa               2.457389
South Korea                2.981149
Sri Lanka                  1.828313
Sweden                     5.506841
Switzerland                6.303642
Taiwan                     2.355343
Thailand                   2.112570
Turkey                     3.831677
UAE                        2.994827
Ukraine                    1.827676
United States              3.580000
Uruguay                    3.323263

In [56]:
bigmac_indexed.xs("Canada", level="Country", drop_level=False)

                    Price in US Dollars
Country Date
Canada  2000-04-01             1.938776
        2001-04-01             2.134615
        2002-04-01             2.121019
        2003-04-01             2.206897
        2004-05-01             2.328467
        2005-06-01             2.625260
        2006-01-01             3.007519
        2006-05-01             3.141595
        2007-01-01             3.089756
        2007-06-01             3.683136
        2008-06-01             4.075532
        2009-07-01             3.350993
        2010-01-01             3.973765
        2010-07-01             4.000576
        2011-07-01             5.000793
        2012-01-01             4.632940
        2012-07-01             5.022316
        2013-01-01             5.394356
        2013-07-01             5.260404
        2014-01-01             5.013121
        2014-07-01             5.251152
        2015-01-01             4.639616
        2015-07-01             4.535939
        2016-01-01             4.144195
        2016-07-01             4.604758
        2017-01-01             4.509804
        2017-07-01             4.655697
        2018-01-01             5.257244
        2018-07-01             5.067246
        2019-01-01             5.084873
        2019-07-09             5.155935
        2020-01-14             5.181585
        2020-07-01             5.076741

## The swaplevel Method
- The `swaplevel` method swaps two levels of a `MultiIndex`.
- Pass the two level identifiers by position or by name.

In [65]:
# pretty simple. just swaps index positions.
swapped = bigmac_indexed.swaplevel(i="Country", j="Date").head()
swapped

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
2001-04-01 Argentina             2.500000
2002-04-01 Argentina             0.798722
2003-04-01 Argentina             1.423611
2004-05-01 Argentina             1.477966

In [67]:
# why is this no different?
swapped = bigmac_indexed.swaplevel(i="Date", j="Country").head()
swapped

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
2001-04-01 Argentina             2.500000
2002-04-01 Argentina             0.798722
2003-04-01 Argentina             1.423611
2004-05-01 Argentina             1.477966

## The transpose Method
- The `transpose` method inverts/flips the horizontal and vertical axes of the `DataFrame`.

In [68]:
bigmac_indexed.transpose()

Country              Argentina                                              \
Date                2000-04-01 2001-04-01 2002-04-01 2003-04-01 2004-05-01
Price in US Dollars        2.5        2.5   0.798722   1.423611   1.477966

Country                                                                     \
Date                2005-06-01 2006-01-01 2006-05-01 2007-01-01 2007-06-01
Price in US Dollars   1.639627   1.550362   2.290201   2.670983   2.668607

Country              ...    Vietnam                                   \
Date                 ... 2016-01-01 2016-07-01 2017-01-01 2017-07-01
Price in US Dollars  ...   2.670524   2.690583   2.658161   2.639393

Country                                                                     \
Date                2018-01-01 2018-07-01 2019-01-01 2019-07-09 2020-01-14
Price in US Dollars   2.861986   2.821242   2.801845   2.797985   2.847774

Country
Date                2020-07-01
Price in US Dollars   2.847282

[1 rows x 1386 columns]

In [69]:
# wow, that's horrible for this data set

## The stack Method
- The `stack` method moves one column index level to the row index.
- If the column axis only has 1 index, pandas will return a `MultiIndex` `Series`.
- Think of it like "stacking" index levels for a column `MultiIndex`.

In [70]:
world = pd.read_csv("worldstats.csv", index_col=["year", "country"]).sort_index()
world.head()

                   Population           GDP
year country
1960 Afghanistan    8994793.0  5.377778e+08
     Algeria       11124892.0  2.723638e+09
     Australia     10276477.0  1.856759e+10
     Austria        7047539.0  6.592694e+09
     Bahamas, The    109526.0  1.698023e+08

In [72]:
# moved index 0 of the columns to the last index of the rows...
# not obvious when to use this, but I guess it makes a good tree structure.
world.stack()

year  country
1960  Afghanistan  Population    8.994793e+06
                   GDP           5.377778e+08
      Algeria      Population    1.112489e+07
                   GDP           2.723638e+09
      Australia    Population    1.027648e+07
                                     ...
2015  World        GDP           7.343364e+13
      Zambia       Population    1.621177e+07
                   GDP           2.120156e+10
      Zimbabwe     Population    1.560275e+07
                   GDP           1.389294e+10
Length: 22422, dtype: float64

- The `to_frame` method converts a `Series` to a `DataFrame`.
- The `DataFrame` will have a 3-level `MultiIndex`.

In [74]:
# but world.stack() makes a Series. so we can convert it back.
# to_frame() to make dataframe, .rename() to change column name
new_world = world.stack().to_frame().rename(columns={0: "Value"})
new_world

                                    Value
year country
1960 Afghanistan Population  8.994793e+06
                 GDP         5.377778e+08
     Algeria     Population  1.112489e+07
                 GDP         2.723638e+09
     Australia   Population  1.027648e+07
...                                   ...
2015 World       GDP         7.343364e+13
     Zambia      Population  1.621177e+07
                 GDP         2.120156e+10
     Zimbabwe    Population  1.560275e+07
                 GDP         1.389294e+10

[22422 rows x 1 columns]

In [75]:
# but those index titles are bad
new_world.index = new_world.index.set_names(names=["Year", "Country", "Category"])
new_world

                                    Value
Year Country     Category
1960 Afghanistan Population  8.994793e+06
                 GDP         5.377778e+08
     Algeria     Population  1.112489e+07
                 GDP         2.723638e+09
     Australia   Population  1.027648e+07
...                                   ...
2015 World       GDP         7.343364e+13
     Zambia      Population  1.621177e+07
                 GDP         2.120156e+10
     Zimbabwe    Population  1.560275e+07
                 GDP         1.389294e+10

[22422 rows x 1 columns]

## The unstack Method
- The `unstack` method moves a row index to the column index (the inverse of the `stack` method).
- By default, the `unstack` method will move the innermost index from rows to columns.
- The `columns` attribute provides the `MultiIndex` object.

In [77]:
new_world.head()

                                    Value
Year Country     Category
1960 Afghanistan Population  8.994793e+06
                 GDP         5.377778e+08
     Algeria     Population  1.112489e+07
                 GDP         2.723638e+09
     Australia   Population  1.027648e+07

In [78]:
new_world.unstack()

                                Value
Category                   Population           GDP
Year Country
1960 Afghanistan         8.994793e+06  5.377778e+08
     Algeria             1.112489e+07  2.723638e+09
     Australia           1.027648e+07  1.856759e+10
     Austria             7.047539e+06  6.592694e+09
     Bahamas, The        1.095260e+05  1.698023e+08
...                               ...           ...
2015 Vietnam             9.170380e+07  1.935994e+11
     West Bank and Gaza  4.422143e+06  1.267740e+10
     World               7.346633e+09  7.343364e+13
     Zambia              1.621177e+07  2.120156e+10
     Zimbabwe            1.560275e+07  1.389294e+10

[11211 rows x 2 columns]

In [80]:
new_world.unstack().unstack().head()

               Value                                                         \
Category  Population
Country  Afghanistan Albania     Algeria Andorra Angola Antigua and Barbuda
Year
1960       8994793.0     NaN  11124892.0     NaN    NaN                 NaN
1961       9164945.0     NaN  11404859.0     NaN    NaN                 NaN
1962       9343772.0     NaN  11690152.0     NaN    NaN                 NaN
1963       9531555.0     NaN  11985130.0     NaN    NaN                 NaN
1964       9728645.0     NaN  12295973.0     NaN    NaN                 NaN

                                               ...                     \
Category                                       ...        GDP
Country  Arab World   Argentina Armenia Aruba  ... Uzbekistan Vanuatu
Year                                           ...
1960            NaN         NaN     NaN   NaN  ...        NaN     NaN
1961            NaN         NaN     NaN   NaN  ...        NaN     NaN
1962            NaN  21287682.0     NaN   NaN  ...        NaN     NaN
1963            NaN  21621845.0     NaN   NaN  ...        NaN     NaN
1964            NaN  21953926.0     NaN   NaN  ...        NaN     NaN

                                                                         \
Category
Country  Venezuela, RB Vietnam Virgin Islands (U.S.) West Bank and Gaza
Year
1960      8.607600e+09     NaN            24200000.0                NaN
1961      8.923367e+09     NaN            25700000.0                NaN
1962      9.873398e+09     NaN            36900000.0                NaN
1963      1.066338e+10     NaN            41400000.0                NaN
1964      9.113581e+09     NaN            53800000.0                NaN


Category
Country          World Yemen, Rep.        Zambia      Zimbabwe
Year
1960      1.364643e+12         NaN  6.987397e+08  1.052990e+09
1961      1.420440e+12         NaN  6.823597e+08  1.096647e+09
1962      1.524573e+12         NaN  6.792797e+08  1.117602e+09
1963      1.638187e+12         NaN  7.043397e+08  1.159512e+09
1964      1.799675e+12         NaN  8.226397e+08  1.217138e+09

[5 rows x 504 columns]

- We can customize the moved index with the `level` parameter.
- The `level` parameter accepts the level's index position or its name.
- We can also pass negative values to pull relative to the end. -3 means "third level from the end".

In [83]:
new_world.unstack(level="Year").head()

                               Value                              \
Year                            1960          1961          1962
Country     Category
Afghanistan Population  8.994793e+06  9.164945e+06  9.343772e+06
            GDP         5.377778e+08  5.488889e+08  5.466667e+08
Albania     Population           NaN           NaN           NaN
            GDP                  NaN           NaN           NaN
Algeria     Population  1.112489e+07  1.140486e+07  1.169015e+07

                                                                  \
Year                            1963          1964          1965
Country     Category
Afghanistan Population  9.531555e+06  9.728645e+06  9.935358e+06
            GDP         7.511112e+08  8.000000e+08  1.006667e+09
Albania     Population           NaN           NaN           NaN
            GDP                  NaN           NaN           NaN
Algeria     Population  1.198513e+07  1.229597e+07  1.262695e+07

                                                                  \
Year                            1966          1967          1968
Country     Category
Afghanistan Population  1.014884e+07  1.036860e+07  1.059979e+07
            GDP         1.400000e+09  1.673333e+09  1.373333e+09
Albania     Population           NaN           NaN           NaN
            GDP                  NaN           NaN           NaN
Algeria     Population  1.298027e+07  1.335420e+07  1.374438e+07

                                      ...                              \
Year                            1969  ...          2006          2007
Country     Category                  ...
Afghanistan Population  1.084951e+07  ...  2.518362e+07  2.587754e+07
            GDP         1.408889e+09  ...  7.057598e+09  9.843842e+09
Albania     Population           NaN  ...  2.992547e+06  2.970017e+06
            GDP                  NaN  ...  8.992642e+09  1.070101e+10
Algeria     Population  1.414444e+07  ...  3.374933e+07  3.426197e+07

                                                                  \
Year                            2008          2009          2010
Country     Category
Afghanistan Population  2.652874e+07  2.720729e+07  2.796221e+07
            GDP         1.019053e+10  1.248694e+10  1.593680e+10
Albania     Population  2.947314e+06  2.927519e+06  2.913021e+06
            GDP         1.288135e+10  1.204421e+10  1.192695e+10
Algeria     Population  3.481106e+07  3.540179e+07  3.603616e+07

                                                                  \
Year                            2011          2012          2013
Country     Category
Afghanistan Population  2.880917e+07  2.972680e+07  3.068250e+07
            GDP         1.793024e+10  2.053654e+10  2.004633e+10
Albania     Population  2.904780e+06  2.900247e+06  2.896652e+06
            GDP         1.289087e+10  1.231978e+10  1.278103e+10
Algeria     Population  3.671713e+07  3.743943e+07  3.818614e+07


Year                            2014          2015
Country     Category
Afghanistan Population  3.162751e+07  3.252656e+07
            GDP         2.005019e+10  1.919944e+10
Albania     Population  2.893654e+06  2.889167e+06
            GDP         1.327796e+10  1.145560e+10
Algeria     Population  3.893433e+07  3.966652e+07

[5 rows x 56 columns]

- The `level` parameter also accepts a list of positions/names.
- `[1,0]` moves the second level (`"country"`) first, then the first level (`"year"`).

In [84]:
new_world.unstack(level=[0,1]).head()

                   Value                                            \
Year                1960
Country      Afghanistan       Algeria     Australia       Austria
Category
Population  8.994793e+06  1.112489e+07  1.027648e+07  7.047539e+06
GDP         5.377778e+08  2.723638e+09  1.856759e+10  6.592694e+09

                                                                    \
Year
Country     Bahamas, The    Bangladesh       Belgium        Belize
Category
Population  1.095260e+05  4.820070e+07  9.153489e+06  9.206800e+04
GDP         1.698023e+08  4.274894e+09  1.165872e+10  2.807248e+07

                                        ...                               \
Year                                    ...           2015
Country            Benin       Bermuda  ... United Kingdom United States
Category                                ...
Population  2.431620e+06  4.440000e+04  ...   6.513823e+07  3.214188e+08
GDP         2.261956e+08  8.446665e+07  ...   2.848755e+12  1.794700e+13

                                                                          \
Year
Country    Upper middle income       Uruguay    Uzbekistan       Vietnam
Category
Population        2.550326e+09  3.431555e+06  3.129950e+07  9.170380e+07
GDP               1.973288e+13  5.344270e+10  6.673280e+10  1.935994e+11


Year
Country    West Bank and Gaza         World        Zambia      Zimbabwe
Category
Population       4.422143e+06  7.346633e+09  1.621177e+07  1.560275e+07
GDP              1.267740e+10  7.343364e+13  2.120156e+10  1.389294e+10

[2 rows x 11211 columns]

- The `sort_index` method can sort the column index.
- Pass an `axis` argument of 1 or `"columns"`.

In [86]:
new_world.unstack(level=[0,1]).sort_index(axis="columns").head()

                   Value                                            \
Year                1960
Country      Afghanistan       Algeria     Australia       Austria
Category
Population  8.994793e+06  1.112489e+07  1.027648e+07  7.047539e+06
GDP         5.377778e+08  2.723638e+09  1.856759e+10  6.592694e+09

                                                                    \
Year
Country     Bahamas, The    Bangladesh       Belgium        Belize
Category
Population  1.095260e+05  4.820070e+07  9.153489e+06  9.206800e+04
GDP         1.698023e+08  4.274894e+09  1.165872e+10  2.807248e+07

                                        ...                               \
Year                                    ...           2015
Country            Benin       Bermuda  ... United Kingdom United States
Category                                ...
Population  2.431620e+06  4.440000e+04  ...   6.513823e+07  3.214188e+08
GDP         2.261956e+08  8.446665e+07  ...   2.848755e+12  1.794700e+13

                                                                          \
Year
Country    Upper middle income       Uruguay    Uzbekistan       Vietnam
Category
Population        2.550326e+09  3.431555e+06  3.129950e+07  9.170380e+07
GDP               1.973288e+13  5.344270e+10  6.673280e+10  1.935994e+11


Year
Country    West Bank and Gaza         World        Zambia      Zimbabwe
Category
Population       4.422143e+06  7.346633e+09  1.621177e+07  1.560275e+07
GDP              1.267740e+10  7.343364e+13  2.120156e+10  1.389294e+10

[2 rows x 11211 columns]

## The pivot Method
- The `pivot` method reshapes data from a tall format to a wide format.
- Ask yourself which direction the data will expand in if you add more entries.
- A tall/long format expands down. A wide format expands out.

In [94]:
sales = pd.read_csv("salesmen.csv")
sales.head()

       Date Salesman  Revenue
0  1/1/2025   Sharon     7172
1  1/2/2025   Sharon     6362
2  1/3/2025   Sharon     5982
3  1/4/2025   Sharon     7917
4  1/5/2025   Sharon     7837

- The `index` parameter sets the horizontal index of the pivoted `DataFrame`.
- The `columns` parameter sets the column whose values will be the columns in the pivoted `DataFrame`.
- The `values` parameter sets the values of the pivoted `DataFrame`.
- Pandas will populate the correct values based on the index and column intersections.

In [96]:
# I tried this with world... but it doesn't seem good with multi-index
sales.pivot(index="Date", columns="Salesman", values="Revenue")

Salesman   Alexander  Dave  Oscar  Ronald  Sharon
Date
1/1/2025        4430  1864   5250    2639    7172
1/10/2025        301  7105   7663    8267    7543
1/11/2025       9489  6851   8888    1340    1053
1/12/2025       8719  7147   3092     279    4362
1/13/2025       2349  6160   6139    7540    6812
...              ...   ...    ...     ...     ...
9/5/2025        2439   211   7743    4252     992
9/6/2025        7585  7293   5072    1112     556
9/7/2025        6669  9774   5230    3608    6499
9/8/2025        3058  8194   7755    5762    9621
9/9/2025        6823  4733   5684    8922    1231

[365 rows x 5 columns]

## The melt Method
- The `melt` method is the inverse of the `pivot` method.
- It converts a 'wide' dataset into a 'tall' dataset.
- The `melt` method is ideal when you have multiple columns storing the *same* data point.
- Ask yourself whether the column's values are a *type* of the column header. If they're not, the data is likely stored in a wide format.

In [97]:
quarters = pd.read_csv("quarters.csv")
quarters.head()

  Salesman      Q1      Q2      Q3      Q4
0    Boris  602908  233879  354479   32704
1    Piers   43790  514863  297151  544493
2    Tommy  392668  113579  430882  247231
3   Travis  834663  266785  749238  570524
4    Cindy  580935  411379  110390  651572

- The `id_vars` parameter accepts the column whose values will be repeated for every column.
- The `var_name` parameter sets the name of the new column for the varying values (the former column names).
- The `value_name` parameter sets the new name of the values column (holding the values from the original `DataFrame`).

In [99]:
quarters.melt(id_vars="Salesman", value_vars=["Q1", "Q2", "Q3", "Q4"]).head()

  Salesman variable   value
0    Boris       Q1  602908
1    Piers       Q1   43790
2    Tommy       Q1  392668
3   Travis       Q1  834663
4    Cindy       Q1  580935

In [100]:
# or if you like things tidy
quarters.melt(
    id_vars="Salesman",
    value_vars=["Q1", "Q2", "Q3", "Q4"],
    var_name="Quarter",
    value_name="Revenue",
).head()

  Salesman Quarter  Revenue
0    Boris      Q1   602908
1    Piers      Q1    43790
2    Tommy      Q1   392668
3   Travis      Q1   834663
4    Cindy      Q1   580935

## The pivot_table Method
- A pivot table is a `DataFrame` whose values are aggregations of groups of values from another table.
- The `pivot_table` method operates similarly to the Pivot Table feature in Excel.

In [101]:
foods = pd.read_csv("foods.csv")
foods.head()

  First Name  Gender          City Frequency       Item  Spend
0      Wanda  Female      Stamford    Weekly     Burger  15.66
1       Eric    Male      Stamford     Daily    Chalupa  10.56
2    Charles    Male      New York     Never      Sushi  42.14
3       Anna  Female  Philadelphia      Once  Ice Cream  11.01
4    Deborah  Female  Philadelphia     Daily    Chalupa  23.49

- The `values` parameter accepts the numeric column whose values will be aggregated.
- The `index` parameter sets the index labels of the pivot table. A `MultiIndex` is permitted.
- The `aggfunc` parameter declares the aggregation function.
- The default aggregation is mean/average.

In [102]:
foods.pivot_table(values="Spend", index=["City", "Gender"])

                         Spend
City         Gender
New York     Female  48.666194
             Male    52.318418
Philadelphia Female  52.637650
             Male    46.601420
Stamford     Female  50.502184
             Male    49.596623

In [104]:
foods.pivot_table(values="Spend", index="Gender", aggfunc="max")

        Spend
Gender
Female  99.51
Male    99.87

- The `sum` aggregation adds the values together.
- The next example finds the spend by item.

In [105]:
foods.pivot_table(values="Spend", index=["City", "Gender"], aggfunc="sum")

                       Spend
City         Gender
New York     Female  7543.26
             Male    8266.31
Philadelphia Female  9632.69
             Male    8201.85
Stamford     Female  8787.38
             Male    7637.88

- The `index` parameter accepts a list of columns.
- The pivot table will have a `MultiIndex`.

In [107]:
# did this already above, but here's an example with filtering
foods[foods["Gender"] == "Female"]["Spend"].mean()

np.float64(50.70962890625)

- The `columns` parameter sets the column labels of the pivot table. A `MultiIndex` is permitted.

In [109]:
foods.pivot_table(
    values="Spend", index="Item", columns=["Gender", "City"], aggfunc="sum"
)

Gender      Female                           Male
City      New York Philadelphia Stamford New York Philadelphia Stamford
Item
Burger     1239.04      1639.24  1216.02  1294.09       938.18  1439.16
Burrito     978.95      1458.76  1820.11  1399.40      1312.93  1300.29
Chalupa     876.58      1673.33  1602.35  1227.77      1114.23  1150.26
Donut      1446.78      1639.26  1656.96  1345.27      1249.36  1421.13
Ice Cream  1521.62      1479.22  1032.03  1603.63      2191.27  1059.22
Sushi      1480.29      1742.88  1459.91  1396.15      1395.88  1267.82

- Other aggregation functions (`count`, `max` and `min`) are also availble.

- The `margins` parameter adds an `All` row/column with subtotals.

In [110]:
foods.pivot_table(
    values="Spend", index="Item", columns="City", aggfunc="sum", margins=True
)

City       New York  Philadelphia  Stamford       All
Item
Burger      2533.13       2577.42   2655.18   7765.73
Burrito     2378.35       2771.69   3120.40   8270.44
Chalupa     2104.35       2787.56   2752.61   7644.52
Donut       2792.05       2888.62   3078.09   8758.76
Ice Cream   3125.25       3670.49   2091.25   8886.99
Sushi       2876.44       3138.76   2727.73   8742.93
All        15809.57      17834.54  16425.26  50069.37